# CONFIGURATIONS CUSTOMIZED ENVIRONMENT DEVELOPMENT (DEV)

# H2 DATABASE CONFIGURATIONS
spring:
  datasource:
    url : ${DATABASE_URL_DEV}
    driverClassName : org.h2.Driver
    username : ${DATABASE_USERNAME_DEV}
    password : ${DATABASE_PASSWORD_DEV}
  h2:
    console:
      enabled : true
  
# JPA HIBERNATE CONFIGURATIONS
  jpa:
    database-platform : org.hibernate.dialect.H2Dialect
    generate-ddl : true
    hibernate:
      ddl-auto : create-drop

