# CONFIGURATIONS CUSTOMIZED ENVIRONMENT DEVELOPMENT (DEV)

# H2 DATABASE CONFIGURATIONS
spring:
  datasource:
    url : jdbc:h2:mem:f1_challenge
    driverClassName : org.h2.Driver
    username : admin
    password : 123456
  h2:
    console:
      enabled : true
  
# JPA HIBERNATE CONFIGURATIONS
  jpa:
    database-platform : org.hibernate.dialect.H2Dialect
    generate-ddl : true
    hibernate:
      ddl-auto : create-drop

