# CONFIGURATIONS BANNER
spring:
  banner:
    location=classpath : /banner.txt

# GENERAL CONFIGURATIONS SERVER (ENVIRONMENTS DEV, HML AND PRD)
server:
  servlet:
    context-path : /f1-challenge
  port : 5000
